### ISSUE TITLE
Synology Drive and git repositories

### ISSUE THREAD

**Issue by galettof** [bakkeby/choosing-a-sync-service-under-linux#1]
Hi there, great writeup! It saved me a lot of time.

I was wondering if you ever experienced issues of git repositories not syncing correctly in Synology Drive. I found an issue reported here: https://community.synology.com/enu/forum/1/post/149269.

I am also curious what linux dsitributions you have been using. It seems the only client offered by Synology are for Debian/Ubuntu.

Than you!

**Comment by bakkeby** [comment]
Ha, that post was actually made by me :)

I don't think that this is an issue specifically with Synology Drive; it only syncs files that it is aware of that has changed. Not sure how exactly it gets notified of this, whether that is via dbus or otherwise, but when git manipulates its internal files it does so without triggering notifications for those files. Some sync services may work around this by periodically scanning through your synched directories looking for files that have changed.

Simply `touch`ing the files does not make any difference. As per the post I use a git hook to make sure that they are synched after committing.

```sh
$ cat .git/hooks/post-commit
#!/bin/sh
find .git -mmin -1 -type f -exec sed -i '' {} \;
```

As for distribution I use Manjaro at the moment, but would go for just Arch if / when I do a new installation. The Synology Drive client is available in the [AUR](https://aur.archlinux.org/packages/synology-drive).

**Comment by galettof** [comment]
Thank you for the quick reply! I completely missed the user name. 😅

If I understand correctly, I would put this post-commit script in the hooks folder of each local git repository. That would take care of triggering the sync by appending an empty string to all files in the .git folder that were modified in the last minute, right?

I looked at the source of the AUR package. If I understand this correctly, someone in the community is kindly repackaging the Debian package released by Synology. It seems someone is doing the same for Fedora (see https://community.synology.com/enu/forum/1/post/121686 and https://github.com/EmixamPP/synology-drive).

**Comment by bakkeby** [comment]
> If I understand correctly, I would put this post-commit script in the hooks folder of each local git repository. That would take care of triggering the sync by appending an empty string to all files in the .git folder that were modified in the last minute, right?

Yes, except that it doesn't append or change anything. It will open the file for writing, then it will close the file which triggers the notification and Synology Drive to sync the file. In practice it is a no-op for the file where this is applied.

> I looked at the source of the AUR package. If I understand this correctly, someone in the community is kindly repackaging the Debian package released by Synology.

I believe that is the case. It should be possible to convert the .deb to an .rpm or to convert it so that it installs on arch locally, but using the AUR just makes it more convenient.

**Comment by galettof** [comment]
I was researching a convenient way to add the post-commit hook to all my local repositories and came across this page: https://stackoverflow.com/questions/2293498/applying-a-git-post-commit-hook-to-all-current-and-future-repositories

The accepted answer suggests adding a global hook as follows:
`git config --global core.hooksPath /path/to/my/centralized/hooks`

Do you think the script as written above will work as a global hook or could there be more subtle issues? Thanks!

**Comment by bakkeby** [comment]
I think that it should work just fine, don't foresee any issues.

I shall try that out though.

**Comment by bakkeby** [comment]
Just to confirm I did try out centralised hooks and it works just fine. Beats having the same hook for every project.

The hook scripts run in the base directory of the git repository so there shouldn't be a problem with paths, even if you are committing from a subdirectory.

**Comment by galettof** [comment]
Thank you, that is good to know!

I also gave it a try and could not make it work. I was likely doing something wrong. For the time being, the post-commit script in each repository works fine. I might give the global script another try in the future.
